'use client';

import { useState, useCallback } from 'react';
import { X, Tag, Plus, Save, RefreshCw, Check } from 'lucide-react';
import type { Sprint } from '@/types/sprint';

interface Props {
  sprint: Sprint;
  autoGeneratedLabel: string;
  onClose: () => void;
  onSaved?: (updatedSprint: Sprint) => void;
}

type SaveStatus = 'idle' | 'saving' | 'success' | 'error';

export default function SprintLabelEditor({ sprint, autoGeneratedLabel, onClose, onSaved }: Props) {
  const [labels, setLabels] = useState<string[]>(sprint.confluence_labels || []);
  const [labelInput, setLabelInput] = useState('');
  const [saveStatus, setSaveStatus] = useState<SaveStatus>('idle');
  const [errorMessage, setErrorMessage] = useState('');

  const originalLabels = sprint.confluence_labels || [];
  const hasChanges = JSON.stringify(labels.sort()) !== JSON.stringify([...originalLabels].sort());

  const handleAddLabel = useCallback(() => {
    const trimmed = labelInput.trim().toLowerCase();
    if (trimmed && !labels.includes(trimmed)) {
      setLabels(prev => [...prev, trimmed]);
      setLabelInput('');
    }
  }, [labelInput, labels]);

  const handleRemoveLabel = useCallback((label: string) => {
    setLabels(prev => prev.filter(l => l !== label));
  }, []);

  const handleSave = async () => {
    if (!hasChanges) {
      onClose();
      return;
    }

    setSaveStatus('saving');
    setErrorMessage('');

    try {
      const response = await fetch(`/api/sprints/${sprint.id}/labels`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ labels }),
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || 'Failed to save labels');
      }

      const result = await response.json();
      setSaveStatus('success');

      if (onSaved && result.sprint) {
        onSaved(result.sprint);
      }

      setTimeout(() => {
        onClose();
      }, 500);
    } catch (error) {
      setSaveStatus('error');
      setErrorMessage(error instanceof Error ? error.message : 'Unknown error');
    }
  };

  const handleReset = () => {
    setLabels(originalLabels);
    setSaveStatus('idle');
    setErrorMessage('');
  };

  return (
    <div
      className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"
      onClick={onClose}
    >
      <div
        className="bg-white rounded-xl shadow-2xl max-w-lg w-full overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-gray-200 bg-gray-50">
          <div className="flex items-center gap-2">
            <Tag className="w-5 h-5 text-blue-600" />
            <h2 className="text-lg font-semibold text-gray-900">Confluence Labels</h2>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-200 rounded-lg transition-colors"
          >
            <X className="w-5 h-5 text-gray-500" />
          </button>
        </div>

        {/* Content */}
        <div className="p-5 space-y-4">
          {/* Auto-generated label info */}
          <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg">
            <p className="text-sm text-blue-800">
              <span className="font-medium">Auto-generated label: </span>
              <code className="px-1.5 py-0.5 bg-blue-100 rounded text-blue-900">
                {autoGeneratedLabel}
              </code>
            </p>
            <p className="text-xs text-blue-600 mt-1">
              This label is automatically derived from the sprint name and always included.
            </p>
          </div>

          {/* Custom labels */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Additional Labels
            </label>
            <div className="flex flex-wrap gap-2 mb-3 min-h-[32px]">
              {labels.map((label) => (
                <span
                  key={label}
                  className="inline-flex items-center gap-1 px-3 py-1 bg-purple-100 text-purple-700 rounded-full text-sm"
                >
                  {label}
                  <button
                    type="button"
                    onClick={() => handleRemoveLabel(label)}
                    className="hover:text-purple-900"
                  >
                    <X className="w-3 h-3" />
                  </button>
                </span>
              ))}
              {labels.length === 0 && (
                <span className="text-sm text-gray-400 italic">No additional labels</span>
              )}
            </div>
            <div className="flex gap-2">
              <input
                type="text"
                value={labelInput}
                onChange={(e) => setLabelInput(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') {
                    e.preventDefault();
                    handleAddLabel();
                  }
                }}
                className="flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm"
                placeholder="Add a label (e.g., euvgen4)"
              />
              <button
                type="button"
                onClick={handleAddLabel}
                disabled={!labelInput.trim()}
                className="px-3 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Plus className="w-4 h-4" />
              </button>
            </div>
          </div>

          {/* Tip */}
          <p className="text-xs text-gray-500">
            Confluence pages with these labels will be displayed in the Sprint Documents section.
          </p>

          {/* Error Message */}
          {errorMessage && (
            <div className="p-3 bg-red-50 border border-red-200 rounded-lg">
              <p className="text-sm text-red-700">{errorMessage}</p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between p-5 border-t border-gray-200 bg-gray-50">
          <div className="text-sm text-gray-500">
            {hasChanges ? 'Unsaved changes' : 'No changes'}
          </div>
          <div className="flex gap-2">
            {hasChanges && (
              <button
                type="button"
                onClick={handleReset}
                className="px-3 py-2 text-gray-700 hover:bg-gray-200 rounded-lg transition-colors flex items-center gap-1.5 text-sm"
              >
                <RefreshCw className="w-4 h-4" />
                Reset
              </button>
            )}
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-gray-700 hover:bg-gray-200 rounded-lg transition-colors text-sm"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={handleSave}
              disabled={!hasChanges || saveStatus === 'saving'}
              className={`px-4 py-2 rounded-lg transition-colors flex items-center gap-1.5 text-sm ${
                !hasChanges || saveStatus === 'saving'
                  ? 'bg-gray-300 text-gray-500 cursor-not-allowed'
                  : saveStatus === 'success'
                  ? 'bg-green-600 text-white'
                  : 'bg-blue-600 text-white hover:bg-blue-700'
              }`}
            >
              {saveStatus === 'saving' ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" />
                  Saving...
                </>
              ) : saveStatus === 'success' ? (
                <>
                  <Check className="w-4 h-4" />
                  Saved
                </>
              ) : (
                <>
                  <Save className="w-4 h-4" />
                  Save
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
