services:
  javis-viewer:
    container_name: javis-viewer
    image: javis-viewer:latest
    restart: always
    ports:
      - "127.0.0.1:3009:3009"
    env_file:
      - .env
    environment:
      - PORT=3009
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks:
      - javis_net

networks:
  javis_net:
    driver: bridge
